name: yust_web
description: Build awesome apps with Flutter and Firebase.
version: 0.3.1
author: "Jannes Köhler <janneskoehler@gmail.com>"
homepage: https://janneskoehler.de

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
  firebase: ^5.0.0
  # scoped_model: ^1.0.1 # not supported
  intl: ^0.15.8

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
